[package]
name = "maud-html-boilerplate"
version = "0.1.0"
edition = "2021"

[dependencies]
maud = "0.26.0"
rocket = { version = "0.5", optional = true }

[features]
rocket = ["dep:rocket", "maud/rocket"]

[package.metadata.docs.rs]
all-features = true
